name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Auto-merge Dependabot PR
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        merge-method: squash
