name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  USER: ${{ secrets.DOCKER_USERNAME }}
  REPO: crossdev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set env
      run: echo "TAG_DATE=$(date +%y%m%d)" >> $GITHUB_ENV
  
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@3.11.1

    - name: Login to Docker hub
      uses: docker/login-action@3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and deploy to dockerhub
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        tags: |
          ${{ env.USER }}/${{ env.REPO }}:latest
          ${{ env.USER }}/${{ env.REPO }}:${{ env.TAG_DATE }}
